//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : parser.sm
//

#ifndef PARSERFSM_H
#define PARSERFSM_H


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace smc_version
{
    // Forward declarations.
    class ParserContextState;
    class ParserFSM;
    class ParserContext;

    class ParserContextState :
        public statemap::State
    {
    public:

        ParserContextState(const char * const name, const int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(ParserFSM&) {};
        virtual void Exit(ParserFSM&) {};


    protected:

        virtual void Default(ParserFSM& context);
    };

    class ParserFSM :
        public statemap::FSMContext
    {
    public:

        explicit ParserFSM(ParserContext& owner)
        : FSMContext(ParserFSM::Skip_start_spaces),
          _owner(owner)
        {};

        ParserFSM(ParserContext& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        inline ParserContext& getOwner()
        {
            return (_owner);
        };

        inline ParserContextState& getState()
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return dynamic_cast<ParserContextState&>(*_state);
        };

    private:
        ParserContext& _owner;
    };
}


#endif // PARSERFSM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
