//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : parser.sm
//


// SMC parser for relation expressions


#include "lexer_context.h"
#include "/home/deracel/automata_theory/labs/lab1/src/impls/smc_version/parser_sm.h"

using namespace statemap;

// Static class declarations.
LexerFSM_Skip_start_spaces LexerFSM::Skip_start_spaces("LexerFSM::Skip_start_spaces", 0);
LexerFSM_Expect_create LexerFSM::Expect_create("LexerFSM::Expect_create", 1);
LexerFSM_Expect_expression_name LexerFSM::Expect_expression_name("LexerFSM::Expect_expression_name", 2);
LexerFSM_Expect_open_skobka LexerFSM::Expect_open_skobka("LexerFSM::Expect_open_skobka", 3);
LexerFSM_Expect_attribute LexerFSM::Expect_attribute("LexerFSM::Expect_attribute", 4);
LexerFSM_In_attribute LexerFSM::In_attribute("LexerFSM::In_attribute", 5);
LexerFSM_After_attribute LexerFSM::After_attribute("LexerFSM::After_attribute", 6);
LexerFSM_Expect_end LexerFSM::Expect_end("LexerFSM::Expect_end", 7);
LexerFSM_Failure LexerFSM::Failure("LexerFSM::Failure", 8);
LexerFSM_Success LexerFSM::Success("LexerFSM::Success", 9);
LexerFSM_Expect_as LexerFSM::Expect_as("LexerFSM::Expect_as", 10);
LexerFSM_Expect_space_aft_as LexerFSM::Expect_space_aft_as("LexerFSM::Expect_space_aft_as", 11);
LexerFSM_Expect_exp_1 LexerFSM::Expect_exp_1("LexerFSM::Expect_exp_1", 12);
LexerFSM_Expect_join LexerFSM::Expect_join("LexerFSM::Expect_join", 13);
LexerFSM_Expect_exp_2 LexerFSM::Expect_exp_2("LexerFSM::Expect_exp_2", 14);

void lexer_contextState::next_char(parserContext& context, char c)
{
    Default(context);
}

void lexer_contextState::reset(parserContext& context)
{
    Default(context);
}

void lexer_contextState::Default(parserContext& context)
{
    throw (
        TransitionUndefinedException(
            context.getState().getName(),
            context.getTransition()));

}

void LexerFSM_Skip_start_spaces::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (c == ' ')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Skip_start_spaces);
        context.getState().Entry(context);
    }
    else if (c == 'c')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.start_create_accum(c);
            context.setState(LexerFSM::Expect_create);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_create);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

void LexerFSM_Expect_create::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (ctxt.is_accumulating_create() and ctxt.create_is_accumulated() and c == ' ')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_expression_name);
        context.getState().Entry(context);
    }
    else if (ctxt.is_accumulating_create() and ctxt.create_mismatch())

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.is_accumulating_create())

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.accumulate_create(c);
            context.setState(LexerFSM::Expect_create);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_create);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

void LexerFSM_Expect_expression_name::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (ctxt.name_started() == false and c == ' ')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_expression_name);
        context.getState().Entry(context);
    }
    else if (ctxt.name_started() == false and (ctxt.isalpha(c) or c == '_' or c == '.'))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.add_to_name(c);
            context.setState(LexerFSM::Expect_expression_name);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_expression_name);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.name_started() == false)

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.name_started() == true and (ctxt.isalnum(c) or c == '_' or c == '.'))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.add_to_name(c);
            context.setState(LexerFSM::Expect_expression_name);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_expression_name);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.name_started() == true and c == ' ')

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_open_skobka);
        context.getState().Entry(context);
    }
    else if (ctxt.name_started() == true and c == '(')

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_attribute);
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

void LexerFSM_Expect_open_skobka::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (c == ' ')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_open_skobka);
        context.getState().Entry(context);
    }
    else if (c == 'a')

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_as);
        context.getState().Entry(context);
    }
    else if (c == '(')

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_attribute);
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

void LexerFSM_Expect_attribute::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (c == ' ')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_attribute);
        context.getState().Entry(context);
    }
    else if (ctxt.attribute_started() == false and (ctxt.isalpha(c) or c == '_' or c == '.'))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.start_attribute(c);
            context.setState(LexerFSM::In_attribute);
        }
        catch (...)
        {
            context.setState(LexerFSM::In_attribute);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.attribute_started() == false)

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

void LexerFSM_In_attribute::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (ctxt.isalnum(c) or c == '_' or c == '.')
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.add_to_attribute(c);
            context.setState(LexerFSM::In_attribute);
        }
        catch (...)
        {
            context.setState(LexerFSM::In_attribute);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (c == ',')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.save_attribute();
            context.setState(LexerFSM::Expect_attribute);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_attribute);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (c == ')')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NEW_EXP);
            ctxt.save_attribute();
            context.setState(LexerFSM::Expect_end);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_end);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (c == ' ')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.save_attribute();
            context.setState(LexerFSM::After_attribute);
        }
        catch (...)
        {
            context.setState(LexerFSM::After_attribute);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

void LexerFSM_After_attribute::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (c == ' ')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::After_attribute);
        context.getState().Entry(context);
    }
    else if (c == ',')

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_attribute);
        context.getState().Entry(context);
    }
    else if (c == ')')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NEW_EXP);
            context.setState(LexerFSM::Expect_end);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_end);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

void LexerFSM_Expect_end::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (c == ' ')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_end);
        context.getState().Entry(context);
    }
    else if (ctxt.is_end_of_line(c))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.end_line();
            context.setState(LexerFSM::Success);
        }
        catch (...)
        {
            context.setState(LexerFSM::Success);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

void LexerFSM_Failure::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.set_exit_state();
        ctxt.reset_for_new_line();
        context.setState(LexerFSM::Skip_start_spaces);
    }
    catch (...)
    {
        context.setState(LexerFSM::Skip_start_spaces);
        throw;
    }
    context.getState().Entry(context);

}

void LexerFSM_Success::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (ctxt.is_end_of_line(c))
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Skip_start_spaces);
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

void LexerFSM_Success::reset(parserContext& context)
{
    lexer_context& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.reset_for_new_line();
        context.setState(LexerFSM::Skip_start_spaces);
    }
    catch (...)
    {
        context.setState(LexerFSM::Skip_start_spaces);
        throw;
    }
    context.getState().Entry(context);

}

void LexerFSM_Expect_as::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (c == 's')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_space_aft_as);
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

void LexerFSM_Expect_space_aft_as::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (c == ' ')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_exp_1);
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

void LexerFSM_Expect_exp_1::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (ctxt.attribute_started() == false and c == ' ')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_exp_1);
        context.getState().Entry(context);
    }
    else if (ctxt.attribute_started() == false and (ctxt.isalpha(c) or c == '_' or c == '.'))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.start_attribute(c);
            context.setState(LexerFSM::Expect_exp_1);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_exp_1);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.attribute_started() == false)

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.attribute_started() == true and (ctxt.isalnum(c) or c == '_' or c == '.'))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.add_to_attribute(c);
            context.setState(LexerFSM::Expect_exp_1);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_exp_1);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.attribute_started() == true and c == ' ')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.save_attribute();
            context.setState(LexerFSM::Expect_join);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_join);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

void LexerFSM_Expect_join::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (c == ' ' and ctxt.is_accumulating_join() == false)
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_join);
        context.getState().Entry(context);
    }
    else if (c == 'j' and ctxt.is_accumulating_join() == false)

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.accumulate_join(c);
            context.setState(LexerFSM::Expect_join);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_join);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.is_accumulating_join() and ctxt.join_is_accumulated() and c == ' ')

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_exp_2);
        context.getState().Entry(context);
    }
    else if (ctxt.is_accumulating_join() and ctxt.join_mismatch())

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.is_accumulating_join())

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.accumulate_join(c);
            context.setState(LexerFSM::Expect_join);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_join);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

void LexerFSM_Expect_exp_2::next_char(parserContext& context, char c)
{
    lexer_context& ctxt = context.getOwner();

    if (ctxt.attribute_started() == false and c == ' ')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(LexerFSM::Expect_exp_2);
        context.getState().Entry(context);
    }
    else if (ctxt.attribute_started() == false and (ctxt.isalpha(c) or c == '_' or c == '.'))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.start_attribute(c);
            context.setState(LexerFSM::Expect_exp_2);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_exp_2);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.attribute_started() == false)

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.attribute_started() == true and (ctxt.isalnum(c) or c == '_' or c == '.'))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.add_to_attribute(c);
            context.setState(LexerFSM::Expect_exp_2);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_exp_2);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (c == ' ')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::COMBINE_EXP);
            ctxt.save_attribute();
            context.setState(LexerFSM::Expect_end);
        }
        catch (...)
        {
            context.setState(LexerFSM::Expect_end);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.is_end_of_line(c))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::COMBINE_EXP);
            ctxt.save_attribute();
            ctxt.end_line();
            context.setState(LexerFSM::Success);
        }
        catch (...)
        {
            context.setState(LexerFSM::Success);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.set_state(STATE::NO);
            context.setState(LexerFSM::Failure);
        }
        catch (...)
        {
            context.setState(LexerFSM::Failure);
            throw;
        }
        context.getState().Entry(context);
    }

}

//
// Local variables:
//  buffer-read-only: t
// End:
//
