//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : parser.sm
//


// SMC parser for relation expressions


#include "ParserFSM.h"
#include "ParserFSM.h"

using namespace statemap;
using namespace std::string;

namespace smc_version
{
    // Static class declarations.
    ParserFSM_Skip_start_spaces ParserFSM::Skip_start_spaces("ParserFSM::Skip_start_spaces", 0);
    ParserFSM_Expect_create ParserFSM::Expect_create("ParserFSM::Expect_create", 1);
    ParserFSM_Expect_1_space_aft_create ParserFSM::Expect_1_space_aft_create("ParserFSM::Expect_1_space_aft_create", 2);
    ParserFSM_Skip_remaining_spaces_aft_create ParserFSM::Skip_remaining_spaces_aft_create("ParserFSM::Skip_remaining_spaces_aft_create", 3);
    ParserFSM_Expect_expression_name ParserFSM::Expect_expression_name("ParserFSM::Expect_expression_name", 4);
    ParserFSM_Expect_space_aft_name ParserFSM::Expect_space_aft_name("ParserFSM::Expect_space_aft_name", 5);
    ParserFSM_Expect_attribute ParserFSM::Expect_attribute("ParserFSM::Expect_attribute", 6);
    ParserFSM_In_attribute ParserFSM::In_attribute("ParserFSM::In_attribute", 7);
    ParserFSM_After_attribute ParserFSM::After_attribute("ParserFSM::After_attribute", 8);
    ParserFSM_Expect_end ParserFSM::Expect_end("ParserFSM::Expect_end", 9);
    ParserFSM_Failure ParserFSM::Failure("ParserFSM::Failure", 10);
    ParserFSM_Success ParserFSM::Success("ParserFSM::Success", 11);
    ParserFSM_Expect_as ParserFSM::Expect_as("ParserFSM::Expect_as", 12);

    void ParserContextState::next_char(ParserFSM& context, char c)
    {
        Default(context);
    }

    void ParserContextState::reset(ParserFSM& context)
    {
        Default(context);
    }

    void ParserContextState::Default(ParserFSM& context)
    {
        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

    }

    void ParserFSM_Skip_start_spaces::next_char(ParserFSM& context, char c)
    {
        ParserContext& ctxt = context.getOwner();

        if (c == " ")
        {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Skip_start_spaces);
            context.getState().Entry(context);
        }
        else if (c == "c")
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.start_create_accum(c);
                context.setState(ParserFSM::Expect_create);
            }
            catch (...)
            {
                context.setState(ParserFSM::Expect_create);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (else)
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.set_error(Command_must_start_with_c_or_spaces);
                context.setState(ParserFSM::Failure);
            }
            catch (...)
            {
                context.setState(ParserFSM::Failure);
                throw;
            }
            context.getState().Entry(context);
        }        else
        {
             ParserFSM_Default::next_char(context, c);
        }

    }

    void ParserFSM_Expect_create::next_char(ParserFSM& context, char c)
    {
        ParserContext& ctxt = context.getOwner();

        if (ctxt.is_accumulating_create() and ctxt.create_is_accumulated())
        {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Expect_1_space_aft_create);
            context.getState().Entry(context);
        }
        else if (ctxt.is_accumulating_create() and ctxt.create_mismatch())
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.set_error(Expected_create);
                context.setState(ParserFSM::Failure);
            }
            catch (...)
            {
                context.setState(ParserFSM::Failure);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (ctxt.is_accumulating_create())
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.accumulate_create(c);
                context.setState(ParserFSM::Expect_create);
            }
            catch (...)
            {
                context.setState(ParserFSM::Expect_create);
                throw;
            }
            context.getState().Entry(context);
        }        else
        {
             ParserFSM_Default::next_char(context, c);
        }

    }

    void ParserFSM_Expect_1_space_aft_create::next_char(ParserFSM& context, char c)
    {
        ParserContext& ctxt = context.getOwner();

        if (c == " ")
        {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Skip_remaining_spaces_aft_create);
            context.getState().Entry(context);
        }
        else if (else)
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.set_error(Expected_at_least_1_space_after_create);
                context.setState(ParserFSM::Failure);
            }
            catch (...)
            {
                context.setState(ParserFSM::Failure);
                throw;
            }
            context.getState().Entry(context);
        }        else
        {
             ParserFSM_Default::next_char(context, c);
        }

    }

    void ParserFSM_Skip_remaining_spaces_aft_create::next_char(ParserFSM& context, char c)
    {
        ParserContext& ctxt = context.getOwner();

        if (c == " ")
        {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Skip_remaining_spaces_aft_create);
            context.getState().Entry(context);
        }
        else if (else)
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.ctxt.save_next_char(c);
                context.setState(ParserFSM::Expect_expression_name);
            }
            catch (...)
            {
                context.setState(ParserFSM::Expect_expression_name);
                throw;
            }
            context.getState().Entry(context);
        }        else
        {
             ParserFSM_Default::next_char(context, c);
        }

    }

    void ParserFSM_Expect_expression_name::next_char(ParserFSM& context, char c)
    {
        ParserContext& ctxt = context.getOwner();

        if (ctxt.name_started() == false and (ctxt.isalpha(c) or c == "_" or c == "."))
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.start_name(c);
                context.setState(ParserFSM::Expect_expression_name);
            }
            catch (...)
            {
                context.setState(ParserFSM::Expect_expression_name);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (ctxt.name_started() == false)
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.set_error(Unknown_symbol_to_start_name);
                context.setState(ParserFSM::Failure);
            }
            catch (...)
            {
                context.setState(ParserFSM::Failure);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (ctxt.name_started() == true and (ctxt.isalnum(c) or c == "_" or c == "."))
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.add_to_name(c);
                context.setState(ParserFSM::Expect_expression_name);
            }
            catch (...)
            {
                context.setState(ParserFSM::Expect_expression_name);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (ctxt.name_started() == true and ctxt.is_space(c))
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Expect_space_aft_name);
            context.getState().Entry(context);
        }
        else if (ctxt.name_started() == true and c == "(")
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Expect_attribute);
            context.getState().Entry(context);
        }
        else if (else)
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.set_error(Expected_space_or_skobka_after_name);
                context.setState(ParserFSM::Failure);
            }
            catch (...)
            {
                context.setState(ParserFSM::Failure);
                throw;
            }
            context.getState().Entry(context);
        }        else
        {
             ParserFSM_Default::next_char(context, c);
        }

    }

    void ParserFSM_Expect_space_aft_name::next_char(ParserFSM& context, char c)
    {
        ParserContext& ctxt = context.getOwner();

        if (c == " ")
        {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Expect_space_aft_name);
            context.getState().Entry(context);
        }
        else if (c == "(")
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Expect_attribute);
            context.getState().Entry(context);
        }
        else if (Ñ == "a")
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Expect_as);
            context.getState().Entry(context);
        }
        else if (else)
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.set_error(Expected_spaces_or_skobka_or_as);
                context.setState(ParserFSM::Failure);
            }
            catch (...)
            {
                context.setState(ParserFSM::Failure);
                throw;
            }
            context.getState().Entry(context);
        }        else
        {
             ParserFSM_Default::next_char(context, c);
        }

    }

    void ParserFSM_Expect_attribute::next_char(ParserFSM& context, char c)
    {
        ParserContext& ctxt = context.getOwner();

        if (c == " ")
        {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Expect_attribute);
            context.getState().Entry(context);
        }
        else if (ctxt.attribute_started() == false and (ctxt.isalpha(c) or c == "_" or c == "."))
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.start_attribute(c);
                context.setState(ParserFSM::In_attribute);
            }
            catch (...)
            {
                context.setState(ParserFSM::In_attribute);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (ctxt.attribute_started() == false)
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.set_error(Unknown_symbol);
                context.setState(ParserFSM::Failure);
            }
            catch (...)
            {
                context.setState(ParserFSM::Failure);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (else)
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.set_error(Unknown_symbol);
                context.setState(ParserFSM::Failure);
            }
            catch (...)
            {
                context.setState(ParserFSM::Failure);
                throw;
            }
            context.getState().Entry(context);
        }        else
        {
             ParserFSM_Default::next_char(context, c);
        }

    }

    void ParserFSM_In_attribute::next_char(ParserFSM& context, char c)
    {
        ParserContext& ctxt = context.getOwner();

        if (ctxt.isalnum(c) or c == "_" or c == ".")
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.add_to_attribute(c);
                context.setState(ParserFSM::In_attribute);
            }
            catch (...)
            {
                context.setState(ParserFSM::In_attribute);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (c == ",")
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.save_attribute(c);
                context.setState(ParserFSM::Expect_attribute);
            }
            catch (...)
            {
                context.setState(ParserFSM::Expect_attribute);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (c == ")")
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.save_attribute(c);
                context.setState(ParserFSM::Expect_end);
            }
            catch (...)
            {
                context.setState(ParserFSM::Expect_end);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (c == " ")
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.save_attribute();
                context.setState(ParserFSM::After_attribute);
            }
            catch (...)
            {
                context.setState(ParserFSM::After_attribute);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (else)
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.set_error(Attribute_is_incorrent);
                context.setState(ParserFSM::Failure);
            }
            catch (...)
            {
                context.setState(ParserFSM::Failure);
                throw;
            }
            context.getState().Entry(context);
        }        else
        {
             ParserFSM_Default::next_char(context, c);
        }

    }

    void ParserFSM_After_attribute::next_char(ParserFSM& context, char c)
    {
        ParserContext& ctxt = context.getOwner();

        if (c == " ")
        {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::After_attribute);
            context.getState().Entry(context);
        }
        else if (c == ",")
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Expect_attribute);
            context.getState().Entry(context);
        }
        else if (c == ")")
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Expect_end);
            context.getState().Entry(context);
        }
        else if (else)
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.set_error(Unexpected_symbol_after_attribute);
                context.setState(ParserFSM::Failure);
            }
            catch (...)
            {
                context.setState(ParserFSM::Failure);
                throw;
            }
            context.getState().Entry(context);
        }        else
        {
             ParserFSM_Default::next_char(context, c);
        }

    }

    void ParserFSM_Expect_end::next_char(ParserFSM& context, char c)
    {
        ParserContext& ctxt = context.getOwner();

        if (c == " ")
        {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Expect_end);
            context.getState().Entry(context);
        }
        else if (ctxt.is_end_of_line(c))
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.end_line();
                context.setState(ParserFSM::Success);
            }
            catch (...)
            {
                context.setState(ParserFSM::Success);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (else)
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.set_error(Unknown_symbols_after_attribute);
                context.setState(ParserFSM::Failure);
            }
            catch (...)
            {
                context.setState(ParserFSM::Failure);
                throw;
            }
            context.getState().Entry(context);
        }        else
        {
             ParserFSM_Default::next_char(context, c);
        }

    }

    void ParserFSM_Failure::next_char(ParserFSM& context, char c)
    {
        ParserContext& ctxt = context.getOwner();


        else
        {
            context.getState().Exit(context);
            context.setState(ParserFSM::Failure);
            context.getState().Entry(context);
        }
        else if (ctxt.is_end_of_line(c))
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.report_failure();
                ctxt.reset_for_new_line();
                context.setState(ParserFSM::Skip_start_spaces);
            }
            catch (...)
            {
                context.setState(ParserFSM::Skip_start_spaces);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void ParserFSM_Failure::reset(ParserFSM& context)
    {
        ParserContext& ctxt = context.getOwner();

        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.reset_error();
            context.setState(ParserFSM::Skip_start_spaces);
        }
        catch (...)
        {
            context.setState(ParserFSM::Skip_start_spaces);
            throw;
        }
        context.getState().Entry(context);

    }

    void ParserFSM_Success::next_char(ParserFSM& context, char c)
    {
        ParserContext& ctxt = context.getOwner();

        if (ctxt.is_end_of_line(c))
        {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Skip_start_spaces);
            context.getState().Entry(context);
        }
        else if (else)
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.set_error(ERR_UNEXPECTED_AFTER_SUCCESS);
                context.setState(ParserFSM::Failure);
            }
            catch (...)
            {
                context.setState(ParserFSM::Failure);
                throw;
            }
            context.getState().Entry(context);
        }        else
        {
             ParserFSM_Default::next_char(context, c);
        }

    }

    void ParserFSM_Success::reset(ParserFSM& context)
    {
        ParserContext& ctxt = context.getOwner();

        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.reset_state();
            context.setState(ParserFSM::Skip_start_spaces);
        }
        catch (...)
        {
            context.setState(ParserFSM::Skip_start_spaces);
            throw;
        }
        context.getState().Entry(context);

    }

    void ParserFSM_Expect_as::next_char(ParserFSM& context, char c)
    {
        ParserContext& ctxt = context.getOwner();

        if (ctxt.is_accumulating_as() and ctxt.as_is_accumulated())
        {
            context.getState().Exit(context);
            // No actions.
            context.setState(ParserFSM::Failure);
            context.getState().Entry(context);
        }
        else
        {
             ParserFSM_Default::next_char(context, c);
        }

    }
}

//
// Local variables:
//  buffer-read-only: t
// End:
//
