//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : parser.sm
//

#ifndef PARSER_SM_H
#define PARSER_SM_H


#define SMC_USES_IOSTREAMS

#include <statemap.h>

// Forward declarations.
class LexerFSM;
class LexerFSM_Initial;
class LexerFSM_Skip_start_spaces;
class LexerFSM_Expect_create;
class LexerFSM_Expect_expression_name;
class LexerFSM_Expect_open_skobka;
class LexerFSM_Expect_attribute;
class LexerFSM_In_attribute;
class LexerFSM_After_attribute;
class LexerFSM_Expect_end;
class LexerFSM_Failure;
class LexerFSM_Success;
class LexerFSM_Expect_as;
class LexerFSM_Expect_space_aft_as;
class LexerFSM_Expect_exp_1;
class LexerFSM_Expect_join;
class LexerFSM_Expect_exp_2;
class LexerFSM_Default;
class lexer_contextState;
class parserContext;
class lexer_context;

class lexer_contextState :
    public statemap::State
{
public:

    lexer_contextState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(parserContext&) {};
    virtual void Exit(parserContext&) {};

    virtual void next_char(parserContext& context, char c);
    virtual void reset(parserContext& context);

protected:

    virtual void Default(parserContext& context);
};

class LexerFSM
{
public:

    static LexerFSM_Initial Initial;
    static LexerFSM_Skip_start_spaces Skip_start_spaces;
    static LexerFSM_Expect_create Expect_create;
    static LexerFSM_Expect_expression_name Expect_expression_name;
    static LexerFSM_Expect_open_skobka Expect_open_skobka;
    static LexerFSM_Expect_attribute Expect_attribute;
    static LexerFSM_In_attribute In_attribute;
    static LexerFSM_After_attribute After_attribute;
    static LexerFSM_Expect_end Expect_end;
    static LexerFSM_Failure Failure;
    static LexerFSM_Success Success;
    static LexerFSM_Expect_as Expect_as;
    static LexerFSM_Expect_space_aft_as Expect_space_aft_as;
    static LexerFSM_Expect_exp_1 Expect_exp_1;
    static LexerFSM_Expect_join Expect_join;
    static LexerFSM_Expect_exp_2 Expect_exp_2;
};

class LexerFSM_Default :
    public lexer_contextState
{
public:

    LexerFSM_Default(const char * const name, const int stateId)
    : lexer_contextState(name, stateId)
    {};

};

class LexerFSM_Initial :
    public LexerFSM_Default
{
public:
    LexerFSM_Initial(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_Skip_start_spaces :
    public LexerFSM_Default
{
public:
    LexerFSM_Skip_start_spaces(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_Expect_create :
    public LexerFSM_Default
{
public:
    LexerFSM_Expect_create(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_Expect_expression_name :
    public LexerFSM_Default
{
public:
    LexerFSM_Expect_expression_name(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_Expect_open_skobka :
    public LexerFSM_Default
{
public:
    LexerFSM_Expect_open_skobka(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_Expect_attribute :
    public LexerFSM_Default
{
public:
    LexerFSM_Expect_attribute(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_In_attribute :
    public LexerFSM_Default
{
public:
    LexerFSM_In_attribute(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_After_attribute :
    public LexerFSM_Default
{
public:
    LexerFSM_After_attribute(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_Expect_end :
    public LexerFSM_Default
{
public:
    LexerFSM_Expect_end(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_Failure :
    public LexerFSM_Default
{
public:
    LexerFSM_Failure(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_Success :
    public LexerFSM_Default
{
public:
    LexerFSM_Success(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
    virtual void reset(parserContext& context);
};

class LexerFSM_Expect_as :
    public LexerFSM_Default
{
public:
    LexerFSM_Expect_as(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_Expect_space_aft_as :
    public LexerFSM_Default
{
public:
    LexerFSM_Expect_space_aft_as(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_Expect_exp_1 :
    public LexerFSM_Default
{
public:
    LexerFSM_Expect_exp_1(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_Expect_join :
    public LexerFSM_Default
{
public:
    LexerFSM_Expect_join(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class LexerFSM_Expect_exp_2 :
    public LexerFSM_Default
{
public:
    LexerFSM_Expect_exp_2(const char * const name, const int stateId)
    : LexerFSM_Default(name, stateId)
    {};

    virtual void next_char(parserContext& context, char c);
};

class parserContext :
    public statemap::FSMContext
{
public:

    explicit parserContext(lexer_context& owner)
    : FSMContext(LexerFSM::Initial),
      _owner(owner)
    {};

    parserContext(lexer_context& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline lexer_context& getOwner()
    {
        return (_owner);
    };

    inline lexer_contextState& getState()
    {
        if (_state == NULL)
        {
            throw statemap::StateUndefinedException();
        }

        return dynamic_cast<lexer_contextState&>(*_state);
    };

    inline void next_char(char c)
    {
        getState().next_char(*this, c);
    };

    inline void reset()
    {
        getState().reset(*this);
    };

private:
    lexer_context& _owner;
};


#endif // PARSER_SM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
