//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : parser.sm
//


// SMC parser for relation expressions


#include "smc_version.h"
#include "ParserFSM.h"

using namespace statemap;
using namespace std::string;

namespace smc_version
{
    // Static class declarations.

    void ParserContextState::Default(ParserFSM& context)
    {
        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

    }
}

//
// Local variables:
//  buffer-read-only: t
// End:
//
